//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TShirt.InventoryApp.Web.ServiceReferenceGP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceGP.IGp")]
    public interface IGp {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGp/TransactionIn", ReplyAction="http://tempuri.org/IGp/TransactionInResponse")]
        string TransactionIn(string document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGp/TransactionIn", ReplyAction="http://tempuri.org/IGp/TransactionInResponse")]
        System.Threading.Tasks.Task<string> TransactionInAsync(string document);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGpChannel : TShirt.InventoryApp.Web.ServiceReferenceGP.IGp, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GpClient : System.ServiceModel.ClientBase<TShirt.InventoryApp.Web.ServiceReferenceGP.IGp>, TShirt.InventoryApp.Web.ServiceReferenceGP.IGp {
        
        public GpClient() {
        }
        
        public GpClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GpClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GpClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GpClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TransactionIn(string document) {
            return base.Channel.TransactionIn(document);
        }
        
        public System.Threading.Tasks.Task<string> TransactionInAsync(string document) {
            return base.Channel.TransactionInAsync(document);
        }
    }
}
