//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TShirt.InventoryApp.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class IV00300
    {
        public string ITEMNMBR { get; set; }
        public string LOCNCODE { get; set; }
        public System.DateTime DATERECD { get; set; }
        public decimal DTSEQNUM { get; set; }
        public string LOTNUMBR { get; set; }
        public decimal QTYRECVD { get; set; }
        public decimal QTYSOLD { get; set; }
        public decimal ATYALLOC { get; set; }
        public decimal UNITCOST { get; set; }
        public int RCTSEQNM { get; set; }
        public string VNDRNMBR { get; set; }
        public byte LTNUMSLD { get; set; }
        public short QTYTYPE { get; set; }
        public string BIN { get; set; }
        public System.DateTime MFGDATE { get; set; }
        public System.DateTime EXPNDATE { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
