//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TShirt.InventoryApp.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class IV10302
    {
        public string STCKCNTID { get; set; }
        public string ITEMNMBR { get; set; }
        public string LOCNCODE { get; set; }
        public string BINNMBR { get; set; }
        public decimal COUNTEDQTY { get; set; }
        public decimal CAPTUREDQTY { get; set; }
        public System.DateTime DATERECD { get; set; }
        public decimal DTSEQNUM { get; set; }
        public short ITMTRKOP { get; set; }
        public string SERLTNUM { get; set; }
        public short SERIALSTATUS { get; set; }
        public decimal VARIANCEQTY { get; set; }
        public byte VERIFIED { get; set; }
        public short QTYTYPE { get; set; }
        public decimal Temp_Allocated_Quantity { get; set; }
        public System.DateTime MFGDATE { get; set; }
        public System.DateTime EXPNDATE { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
