//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TShirt.InventoryApp.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class IV10300
    {
        public string STCKCNTID { get; set; }
        public string STCKCNTDSCRPTN { get; set; }
        public short STCKCNTSTTS { get; set; }
        public System.DateTime DOCDATE { get; set; }
        public System.DateTime GLPOSTDT { get; set; }
        public decimal NOTEINDX { get; set; }
        public System.DateTime CNTSTRTDT { get; set; }
        public System.DateTime CNTSTRTTM { get; set; }
        public byte ATPSTVRNC { get; set; }
        public byte RSSTCKCNT { get; set; }
        public System.DateTime DFLTCNTDT { get; set; }
        public System.DateTime DFLTCNTTM { get; set; }
        public System.DateTime LSTCNTDT { get; set; }
        public byte ENABLEMULTIBIN { get; set; }
        public string LOCNCODE { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
