//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TShirt.InventoryApp.Service.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IV10301
    {
        public string STCKCNTID { get; set; }
        public string ITEMNMBR { get; set; }
        public string LOCNCODE { get; set; }
        public string BINNMBR { get; set; }
        public decimal CAPTUREDQTY { get; set; }
        public decimal COUNTEDQTY { get; set; }
        public System.DateTime COUNTDATE { get; set; }
        public System.DateTime COUNTTIME { get; set; }
        public short DECPLQTY { get; set; }
        public short ITMTRKOP { get; set; }
        public int IVIVINDX { get; set; }
        public decimal Stock_Serial_Lot_Count { get; set; }
        public decimal STCKSRLLTVRNC { get; set; }
        public int IVVARIDX { get; set; }
        public decimal VARIANCEQTY { get; set; }
        public byte VERIFIED { get; set; }
        public decimal Temp_Allocated_Quantity { get; set; }
        public byte ACTIVE { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
