//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TShirt.InventoryApp.Service.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IV40700
    {
        public string LOCNCODE { get; set; }
        public string LOCNDSCR { get; set; }
        public decimal NOTEINDX { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIPCODE { get; set; }
        public string COUNTRY { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public string PHONE3 { get; set; }
        public string FAXNUMBR { get; set; }
        public string Location_Segment { get; set; }
        public string STAXSCHD { get; set; }
        public string PCTAXSCH { get; set; }
        public byte INCLDDINPLNNNG { get; set; }
        public string PORECEIPTBIN { get; set; }
        public string PORETRNBIN { get; set; }
        public string SOFULFILLMENTBIN { get; set; }
        public string SORETURNBIN { get; set; }
        public string BOMRCPTBIN { get; set; }
        public string MATERIALISSUEBIN { get; set; }
        public string MORECEIPTBIN { get; set; }
        public string REPAIRISSUESBIN { get; set; }
        public byte WMSINT { get; set; }
        public short PICKTICKETSITEOPT { get; set; }
        public short BINBREAK { get; set; }
        public string CCode { get; set; }
        public string DECLID { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
