//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TShirt.InventoryApp.Service.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IV41000
    {
        public short SETUPKEY { get; set; }
        public short NUMBERSHIFTS { get; set; }
        public decimal HRSPRSHFT { get; set; }
        public System.DateTime STRTTIME { get; set; }
        public short DWNONWKNDS { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
