//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TShirt.InventoryApp.Service.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TSGVLEntities : DbContext
    {
        public TSGVLEntities()
            : base("name=TSGVLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IV00101> IV00101 { get; set; }
        public virtual DbSet<POP10100> POP10100 { get; set; }
        public virtual DbSet<POP10110> POP10110 { get; set; }
        public virtual DbSet<IV00102> IV00102 { get; set; }
        public virtual DbSet<IV10300> IV10300 { get; set; }
        public virtual DbSet<IV10301> IV10301 { get; set; }
        public virtual DbSet<IV40700> IV40700 { get; set; }
        public virtual DbSet<IV41000> IV41000 { get; set; }
        public virtual DbSet<PM00200> PM00200 { get; set; }
        public virtual DbSet<RM00101> RM00101 { get; set; }
        public virtual DbSet<ItemQuantities> ItemQuantities { get; set; }
    }
}
