//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TShirt.InventoryApp.Service.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POP10110
    {
        public string PONUMBER { get; set; }
        public int ORD { get; set; }
        public short POLNESTA { get; set; }
        public short POTYPE { get; set; }
        public string ITEMNMBR { get; set; }
        public string ITEMDESC { get; set; }
        public string VENDORID { get; set; }
        public string VNDITNUM { get; set; }
        public string VNDITDSC { get; set; }
        public short NONINVEN { get; set; }
        public string LOCNCODE { get; set; }
        public string UOFM { get; set; }
        public decimal UMQTYINB { get; set; }
        public decimal QTYORDER { get; set; }
        public decimal QTYCANCE { get; set; }
        public decimal QTYCMTBASE { get; set; }
        public decimal QTYUNCMTBASE { get; set; }
        public decimal UNITCOST { get; set; }
        public decimal EXTDCOST { get; set; }
        public int INVINDX { get; set; }
        public System.DateTime REQDATE { get; set; }
        public System.DateTime PRMDATE { get; set; }
        public System.DateTime PRMSHPDTE { get; set; }
        public string REQSTDBY { get; set; }
        public string COMMNTID { get; set; }
        public short DOCTYPE { get; set; }
        public decimal POLNEARY_1 { get; set; }
        public decimal POLNEARY_2 { get; set; }
        public decimal POLNEARY_3 { get; set; }
        public decimal POLNEARY_4 { get; set; }
        public decimal POLNEARY_5 { get; set; }
        public decimal POLNEARY_6 { get; set; }
        public decimal POLNEARY_7 { get; set; }
        public decimal POLNEARY_8 { get; set; }
        public decimal POLNEARY_9 { get; set; }
        public short DECPLCUR { get; set; }
        public short DECPLQTY { get; set; }
        public short ITMTRKOP { get; set; }
        public short VCTNMTHD { get; set; }
        public short BRKFLD1 { get; set; }
        public short PO_Line_Status_Orig { get; set; }
        public decimal QTY_Canceled_Orig { get; set; }
        public decimal OPOSTSUB { get; set; }
        public string JOBNUMBR { get; set; }
        public string COSTCODE { get; set; }
        public short COSTTYPE { get; set; }
        public string CURNCYID { get; set; }
        public short CURRNIDX { get; set; }
        public decimal XCHGRATE { get; set; }
        public short RATECALC { get; set; }
        public decimal DENXRATE { get; set; }
        public decimal ORUNTCST { get; set; }
        public decimal OREXTCST { get; set; }
        public short LINEORIGIN { get; set; }
        public short FREEONBOARD { get; set; }
        public short ODECPLCU { get; set; }
        public byte Capital_Item { get; set; }
        public short Product_Indicator { get; set; }
        public string Source_Document_Number { get; set; }
        public short Source_Document_Line_Num { get; set; }
        public System.DateTime RELEASEBYDATE { get; set; }
        public System.DateTime Released_Date { get; set; }
        public short Change_Order_Flag { get; set; }
        public short Purchase_IV_Item_Taxable { get; set; }
        public string Purchase_Item_Tax_Schedu { get; set; }
        public string Purchase_Site_Tax_Schedu { get; set; }
        public short PURCHSITETXSCHSRC { get; set; }
        public byte BSIVCTTL { get; set; }
        public decimal TAXAMNT { get; set; }
        public decimal ORTAXAMT { get; set; }
        public decimal BCKTXAMT { get; set; }
        public decimal OBTAXAMT { get; set; }
        public string Landed_Cost_Group_ID { get; set; }
        public short PLNNDSPPLID { get; set; }
        public string SHIPMTHD { get; set; }
        public decimal BackoutTradeDiscTax { get; set; }
        public decimal OrigBackoutTradeDiscTax { get; set; }
        public short LineNumber { get; set; }
        public System.DateTime ORIGPRMDATE { get; set; }
        public System.DateTime FSTRCPTDT { get; set; }
        public System.DateTime LSTRCPTDT { get; set; }
        public short RELEASE { get; set; }
        public string ADRSCODE { get; set; }
        public string CMPNYNAM { get; set; }
        public string CONTACT { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIPCODE { get; set; }
        public string CCode { get; set; }
        public string COUNTRY { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public string PHONE3 { get; set; }
        public string FAX { get; set; }
        public short ADDRSOURCE { get; set; }
        public short Flags { get; set; }
        public string ProjNum { get; set; }
        public string CostCatID { get; set; }
        public System.DateTime DEX_ROW_TS { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
