//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TShirt.InventoryApp.Service.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseProduct
    {
        public int Id { get; set; }
        public string Warehouse { get; set; }
        public string Product { get; set; }
        public int Quantity { get; set; }
    }
}
